export const FETCH_LIST_USERS = 'FETCH_LIST_USERS';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const REQUEST_LOADING_LIST_USERS = 'REQUEST_LOADING_LIST_USERS';
export const REQUEST_REJECTED_LIST_USERS = 'REQUEST_REJECTED_LIST_USERS';
