export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_COMMITS = 'FETCH_COMMITS';
export const REQUEST_LOADING_REPOS = 'REQUEST_LOADING_REPOS';
export const REQUEST_REJECTED_REPOS = 'REQUEST_REJECTED_REPOS';
